# Generated by Django 5.1.4 on 2024-12-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('categoria', models.CharField(choices=[('elétrico', 'Elétrico'), ('manual', 'Manual')], max_length=10)),
                ('estado', models.CharField(choices=[('disponível', 'Disponível'), ('alugado', 'Alugado'), ('manutenção', 'Em Manutenção')], max_length=20)),
                ('data_aquisicao', models.DateField(auto_now_add=True)),
                ('preco_aluguel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('endereco', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=None)),
                ('data_fim', models.DateTimeField(default=None)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado')], max_length=20)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.carrinho')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.cliente')),
            ],
        ),
    ]
